extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  file/traces:
    path: /var/lib/otel/traces.json
  file/logs:
    path: /var/lib/otel/logs.jsonl
  file/metrics:
    path: /var/lib/otel/metrics.json
  otlphttp/receiver:
    endpoint: "${env:RECEIVER_ENDPOINT}"
    headers:
      Authorization: "Bearer ${env:RECEIVER_AUTH_TOKEN}"

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/traces, otlphttp/receiver]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/logs, otlphttp/receiver]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/metrics, otlphttp/receiver]

