receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  file/traces:
    path: /var/lib/otel/traces.json
  file/logs:
    path: /var/lib/otel/logs.jsonl
  file/metrics:
    path: /var/lib/otel/metrics.json
  otlphttp/receiver:
    endpoint: "${env:RECEIVER_ENDPOINT}"
    encoding: json
    compression: none

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/traces, otlphttp/receiver]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/logs]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/metrics]

