import type { EvidenceQueryRef } from "3am-core";

export type EvidenceCombinedPromptEvidence = {
  ref: EvidenceQueryRef;
  surface: "traces" | "metrics" | "logs";
  summary: string;
};

export type EvidenceCombinedPromptInput = {
  question: string;
  isSystemFollowup?: boolean;
  history?: Array<{
    role: "user" | "assistant";
    content: string;
  }>;
  diagnosis: {
    whatHappened: string;
    rootCauseHypothesis: string;
    immediateAction: string;
    causalChain: string[];
  } | null;
  evidence: EvidenceCombinedPromptEvidence[];
};

/**
 * Builds a single prompt that merges the planning and generation steps.
 *
 * For subprocess providers (codex, claude-code), each LLM invocation costs
 * 7-9s of subprocess overhead. This merged prompt eliminates the second
 * round-trip by having the model classify intent AND generate answer segments
 * in a single response.
 *
 * Output schema supports two shapes:
 *   - Clarification: { mode: "clarification", clarificationQuestion: "..." }
 *   - Answer:        { mode: "answer"|"action"|"missing_evidence", segments: [...] }
 */
export function buildEvidenceCombinedPrompt(
  input: EvidenceCombinedPromptInput,
  options?: { locale?: "en" | "ja" },
): string {
  const diagnosisSection = input.diagnosis
    ? [
        `what_happened: ${input.diagnosis.whatHappened}`,
        `root_cause_hypothesis: ${input.diagnosis.rootCauseHypothesis}`,
        `immediate_action: ${input.diagnosis.immediateAction}`,
        `causal_chain: ${input.diagnosis.causalChain.join(" -> ") || "(none)"}`,
      ].join("\n")
    : "Diagnosis is unavailable. Do not infer beyond the curated evidence list.";

  const historySection = input.history && input.history.length > 0
    ? input.history.slice(-8).map((turn, index) => `  [${index + 1}] ${turn.role}: ${turn.content}`).join("\n")
    : "  (none)";

  const evidenceSection = input.evidence.length > 0
    ? input.evidence
        .map(({ ref, surface, summary }, index) => `  [${index + 1}] ${ref.kind}:${ref.id} surface=${surface} summary=${summary}`)
        .join("\n")
    : "  (none)";

  const localeInstruction = options?.locale === "ja"
    ? `
Respond entirely in Japanese. Keep all JSON keys in English.
Use direct, concise Japanese. Do not use polite or formal phrasing.
`
    : "";

  const systemFollowupInstruction = input.isSystemFollowup
    ? `
IMPORTANT: This question was generated by the system as a suggested follow-up. DO NOT choose "clarification". Provide the best answer available using the current evidence. If you are uncertain, choose "answer" and note the uncertainty in the segments.
`
    : "";

  return `You are an incident evidence copilot that classifies and answers operator questions in one pass.

Step 1 — Classify intent and decide mode:
- "answer": the user is asking for explanation or diagnosis and the current evidence is enough.
- "action": the user is asking what to do next, how to respond, or what should happen operationally.
- "missing_evidence": the user is asking why logs/metrics/traces are missing or what absence means.
- "clarification": the user's question is still too ambiguous even after using the recent conversation history.

Classification rules:
- If recent history makes the target obvious, do NOT clarify.
- If the question is "what should I do", "what next", "so what", and the previous turn established the topic, choose "action".
- If the question asks why logs or other evidence are missing, choose "missing_evidence".
- If the user is asking about the incident generally, choose "answer".
- Questions resembling system-suggested follow-ups (trace path, log cluster, metric) should be answered, not clarified.
- Temporal qualifiers like "first", "earliest", "latest" default to the incident window scope.

Step 2 — Generate a grounded answer (skip if mode=clarification):
Product contract:
- fact = directly supported by curated evidence.
- inference = supported by curated evidence plus existing diagnosis, within a conservative reading.
- unknown = current evidence is insufficient to state the claim responsibly.
- Every segment must cite at least one evidence ref from the curated list below.
- Never invent evidence IDs. Never output a claim without evidenceRefs.
- Never turn this into generic advice, small talk, or a troubleshooting playbook.
- If the question cannot be answered responsibly, use status="no_answer" with a clear noAnswerReason.
- For mode="action", return operational next steps anchored in evidence.
- For mode="missing_evidence", explain the missing signal and the next verification step.
- For mode="answer", explain what happened anchored in evidence.

Curated diagnosis:
${diagnosisSection}

Recent conversation history:
${historySection}

Curated evidence refs you may cite:
${evidenceSection}

User question:
${input.question}

Return ONLY valid JSON in ONE of these two shapes:

Shape A — when mode is clarification:
{
  "mode": "clarification",
  "clarificationQuestion": "one short question to unblock the answer"
}

Shape B — when mode is answer, action, or missing_evidence:
{
  "mode": "answer" | "action" | "missing_evidence",
  "status": "answered" | "no_answer",
  "segments": [
    {
      "kind": "fact" | "inference" | "unknown",
      "text": "one sentence",
      "evidenceRefs": [
        { "kind": "span" | "metric_group" | "log_cluster" | "absence", "id": "..." }
      ]
    }
  ],
  "noAnswerReason": "string — required only when status=no_answer"
}

Hard rules:
- Keep segments sentence-level and concise. Prefer 2-4 segments.
- If more than half of the answer would be unknown, use status="no_answer" instead.
- A fact must be something the cited evidence directly supports.
- An inference must remain narrower than the existing diagnosis; do not extend it.
- Unknown should explicitly say what cannot be concluded yet.
- Never output any text outside JSON.
${localeInstruction}${systemFollowupInstruction}`;
}
